# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4241fd15ced76cfd39219e25918dfd5d5b4204533e59b71cd76752436a4ef1152d033cbe2caedcf3df3def1200e4aa12e71a2b27292d2bef289f41fcca4fe5b6

test:
  secret_key_base: fe7e6024375bcbd2045a86621577752f55f38c4762ce5bf3a404a8c7f708c273dc85af111a0a31abd7bd2089b1ca1f3bef7a3708a226c44b100494f04ff43034

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
